# It contains all the configs required in the project

data:
  ROOT_DATA_DIR : FashionMNISTDir
  PRED_DATA_DIR : Prediction
  PRED_DATA_FILE_NAME : prediction.csv

params:
  ROOT_DATA_DIR : FashionMNISTDir
  EPOCH : 10
  LEARNING_RATE : 0.001
  IMAGE_SIZE : (28,28)
  SEED : 43
  BATCH_SIZE : 64

artifacts:
  model_dir: artifacts
  base_model_name: base_model.pth
  trained_model_name: trained_model.pth
